sudo: required
service: 
  - docker

befor_install:
  - docker build -t insonusk/container-with-test-Travice-CI -f ./Dockerfile .

script:
  - docker run insonusk/container-with-test-Travice-CI dotnet test

deploy:
  provider: script
  script: echo 'Deploy new version'
  on: 
    branch: master
