sudo: required
service: 
  - docker

befor_install:
  - docker build -t insonusk/container-with-test -f ./Dockerfile .

script:
  - docker run insonusk/container-with-test dotnet test

deploy:
  provider: script
  script: bash Scripts/docker-build-release-push.sh
  on: 
    branch: master